version: "3"
services:
  robotframework:
    image: ppodgorsek/robot-framework
    volumes:
      - ./automation-practice/tests-suites:/opt/robotframework/tests/:Z
      - ./automation-practice/reports:/opt/robotframework/reports:Z
    environment:
      - shm-size=1g

